/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RBD_AGENDA_H_RPCGEN
#define _RBD_AGENDA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct contato {
	char nome[50];
	char cpf[14];
	char telefone[15];
	char endereco[50];
};
typedef struct contato contato;

struct agenda {
	contato contatos[100];
	int tam;
};
typedef struct agenda agenda;

#define RBDPROG 0x30090949
#define RDBVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INICIALIZAR 1
extern  void * inicializar_1(void *, CLIENT *);
extern  void * inicializar_1_svc(void *, struct svc_req *);
#define INSERE 2
extern  int * insere_1(contato *, CLIENT *);
extern  int * insere_1_svc(contato *, struct svc_req *);
#define REMOVE 3
extern  int * remove_1(char **, CLIENT *);
extern  int * remove_1_svc(char **, struct svc_req *);
#define BUSCA 4
extern  contato * busca_1(char **, CLIENT *);
extern  contato * busca_1_svc(char **, struct svc_req *);
#define LISTA 5
extern  agenda * lista_1(void *, CLIENT *);
extern  agenda * lista_1_svc(void *, struct svc_req *);
extern int rbdprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INICIALIZAR 1
extern  void * inicializar_1();
extern  void * inicializar_1_svc();
#define INSERE 2
extern  int * insere_1();
extern  int * insere_1_svc();
#define REMOVE 3
extern  int * remove_1();
extern  int * remove_1_svc();
#define BUSCA 4
extern  contato * busca_1();
extern  contato * busca_1_svc();
#define LISTA 5
extern  agenda * lista_1();
extern  agenda * lista_1_svc();
extern int rbdprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_contato (XDR *, contato*);
extern  bool_t xdr_agenda (XDR *, agenda*);

#else /* K&R C */
extern bool_t xdr_contato ();
extern bool_t xdr_agenda ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RBD_AGENDA_H_RPCGEN */
