/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rbd_agenda.h"

bool_t
xdr_contato (XDR *xdrs, contato *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nome, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->cpf, 14,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->telefone, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->endereco, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_agenda (XDR *xdrs, agenda *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->contatos, 100,
		sizeof (contato), (xdrproc_t) xdr_contato))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tam))
		 return FALSE;
	return TRUE;
}
